### ISSUE TITLE
Vectorized path float decoding: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#137]
Seeing this in main at [7495028](https://github.com/maplibre/maplibre-tile-spec/commit/74950281cdd89562fee1633c8125f898b94097fa):

> java -jar build/libs/encode.jar -mvt ../test/fixtures/bing/6-33-22.mvt -decode -advanced -vectorized

```
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:743)
	at java.base/java.nio.ByteBufferAsFloatBufferL.get(ByteBufferAsFloatBufferL.java:139)
	at com.mlt.decoder.vectorized.VectorizedFloatDecoder.decodeNullableFloatStream(VectorizedFloatDecoder.java:35)
	at com.mlt.decoder.vectorized.VectorizedPropertyDecoder.decodeToRandomAccessFormat(VectorizedPropertyDecoder.java:223)
	at com.mlt.decoder.MltDecoder.decodeMlTileVectorized(MltDecoder.java:163)
	at com.mlt.tools.Encode.main(Encode.java:273)
```

**Comment by springmeyer** [comment]
No long present in main at [8e5cc19](https://github.com/maplibre/maplibre-tile-spec/commit/8e5cc195e7ba323e2d3751d70128d6a9d9e941d8)
