### ISSUE TITLE
Multipolygon parsing regression

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#139]
After #79 a multi-polygon which used to decode correctly now results in an error.

To replicate:

```
› cd maplibre-tile-spec/java
› ./gradlew cli
› git clone git@github.com:mapbox/mvt-fixtures.git
› java -jar build/libs/encode.jar -mvt mvt-fixtures/fixtures/022/tile.mvt -decode
java.lang.ArrayIndexOutOfBoundsException: Index 24 out of bounds for length 24
	at com.mlt.decoder.GeometryDecoder.getLineString(GeometryDecoder.java:631)
	at com.mlt.decoder.GeometryDecoder.getLinearRing(GeometryDecoder.java:598)
	at com.mlt.decoder.GeometryDecoder.decodeGeometry(GeometryDecoder.java:228)
	at com.mlt.decoder.MltDecoder.decodeMlTile(MltDecoder.java:78)
	at com.mlt.tools.Encode.main(Encode.java:290)
```

**Comment by springmeyer** [comment]
Done in 5f6f154
