### ISSUE TITLE
Decoding error: Specified physical level technique not yet supported

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#145]
With the latest code, in the non-vectorized path, we are hitting:

```
java.lang.IllegalArgumentException: Specified physical level technique not yet supported: NONE
	at com.mlt.decoder.IntegerDecoder.decodeIntStream(IntegerDecoder.java:86)
	at com.mlt.decoder.GeometryDecoder.decodeGeometryColumn(GeometryDecoder.java:29)
	at com.mlt.decoder.MltDecoder.decodeMlTile(MltDecoder.java:77)
	at com.mlt.tools.Encode.main(Encode.java:269)
```

Testcase:

```
cd java
./gradlew cli
git clone git@github.com:mapbox/mvt-fixtures.git
java -jar build/libs/encode.jar -mvt mvt-fixtures/real-world/norway/12-2174-1070.mvt -decode
```

**Comment by springmeyer** [comment]
Still present after #158

**Comment by springmeyer** [comment]
Dupe of #148
