### ISSUE TITLE
Decoding error: out of bounds in decodeGeometry

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#147]
With the latest code, in the non-vectorized path, we are hitting:

```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.mlt.decoder.GeometryDecoder.decodeGeometry(GeometryDecoder.java:150)
	at com.mlt.decoder.MltDecoder.decodeMlTile(MltDecoder.java:78)
	at com.mlt.tools.Encode.main(Encode.java:269)| java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.mlt.decoder.GeometryDecoder.decodeGeometry(GeometryDecoder.java:150)
	at com.mlt.decoder.MltDecoder.decodeMlTile(MltDecoder.java:78)
	at com.mlt.tools.Encode.main(Encode.java:269)
```

Testcase:

```
cd java
./gradlew cli
git clone git@github.com:mapbox/mvt-fixtures.git
java -jar build/libs/encode.jar -mvt mvt-fixtures/real-world/chicago/13-2102-3043.mvt -decode
```

**Comment by springmeyer** [comment]
Fixed by #158
