### ISSUE TITLE
ClassCastException when encoding tiles

### ISSUE THREAD

**Issue by blacha** [maplibre/maplibre-tile-spec#160]
I have two tiles with two diffrent class cast exceptions

[nz-parcels_10_1009_630.pbf.gz](https://github.com/user-attachments/files/15859819/nz-parcels_10_1009_630.pbf.gz)

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
        at com.mlt.converter.encodings.PropertyEncoder.encodeInt64Column(PropertyEncoder.java:316)
        at com.mlt.converter.encodings.PropertyEncoder.encodeScalarPropertyColumn(PropertyEncoder.java:149)
        at com.mlt.converter.encodings.PropertyEncoder.encodePropertyColumns(PropertyEncoder.java:38)
        at com.mlt.converter.MltConverter.convertMvt(MltConverter.java:207)
        at com.mlt.tools.Encode.main(Encode.java:221)
```

and
[nz-parcels_10_1009_628.pbf.gz](https://github.com/user-attachments/files/15859818/nz-parcels_10_1009_628.pbf.gz)

```
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Long (java.lang.Double and java.lang.Long are in module java.base of loader 'bootstrap')
        at com.mlt.converter.encodings.PropertyEncoder.encodeInt64Column(PropertyEncoder.java:316)
        at com.mlt.converter.encodings.PropertyEncoder.encodeScalarPropertyColumn(PropertyEncoder.java:149)
        at com.mlt.converter.encodings.PropertyEncoder.encodePropertyColumns(PropertyEncoder.java:38)
        at com.mlt.converter.MltConverter.convertMvt(MltConverter.java:207)
        at com.mlt.tools.Encode.main(Encode.java:221)
```

Theses errors are from the current main 7f0d6906d386aea3ac678518513b42d5dd44f966

with a 

```
just clean
just test-java-cli
```
 
then `java -jar ./build/libs/encode.jar -mvt nz-parcels_10_1009_628.pbf`

**Comment by springmeyer** [comment]
@blacha thanks for ticketing this. It should be an easy fix, I hope to find time to take a look late next week.

**Comment by TimSylvester** [comment]
This should be fixed by #555.  It's pretty clear from the stack trace that a string value was encountered while processing an int64 column.  With `--elide-mismatch` it would be treated as null, with `--coerce-mismatch` the column would be a string.
