### ISSUE TITLE
Decoding error: VectorType not supported yet

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#182]
This error impacts only the vectorized decoder:

```
MltDecoderTest > currentlyFailingBingDecoding1() FAILED
    java.lang.IllegalArgumentException: VectorType not supported yet: CONST
        at com.mlt.decoder.vectorized.VectorizedPropertyDecoder.decodeToRandomAccessFormat(VectorizedPropertyDecoder.java:169)
        at com.mlt.decoder.MltDecoder.decodeMlTileVectorized(MltDecoder.java:165)
        at com.mlt.decoder.MltDecoderTest.testTile(MltDecoderTest.java:199)
        at com.mlt.decoder.MltDecoderTest.currentlyFailingBingDecoding1(MltDecoderTest.java:72)
```

**Comment by springmeyer** [comment]
One curious thing about this failure to note: it replicates in the unit tests for the decoder. But I could not replicate with the encode.jar command. When I saw this I then modified the encode.jar to encode the tile in the same way as the decoder unit tests encode the MLT but I was still not able to replicate. So I figure that means either there was a difference still in the way the encode.jar did encoding or something more subtle is happening causing a difference in code paths during decoding.
