### ISSUE TITLE
Pull feature IDs from no.ecc.vectortile:java-vector-tile

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#58]
If we upgrade the `no.ecc` MVT library (#57) we should be able to reduce the usage of the `io.github.sebasbaumh.mapbox.vectortile` library and simplify the code:

@mactrem what do you think about pursuing something like this?

```diff
diff --git a/converter/java/src/main/java/com/mlt/converter/mvt/MvtUtils.java b/converter/java/src/main/java/com/mlt/converter/mvt/MvtUtils.java
index e43f8e7..39aeb8a 100644
--- a/converter/java/src/main/java/com/mlt/converter/mvt/MvtUtils.java
+++ b/converter/java/src/main/java/com/mlt/converter/mvt/MvtUtils.java
@@ -45,10 +45,9 @@ public class MvtUtils {
             var features = new ArrayList<Feature>();
             var tileExtent = 0;
 
-            var ids = getIds(mvtTile, layerName);
             var i = 0;
             for(var mvtFeature : layerFeatures){
-                var properties = new HashMap(mvtFeature.getAttributes());
+                var properties = new HashMap<String, Object>(mvtFeature.getAttributes());
                 var id = 0l;
                 if(properties.containsKey(ID_KEY)){
                     if(properties.get(ID_KEY) instanceof  String){
@@ -66,7 +65,7 @@ public class MvtUtils {
                     }
                 }
                 else{
-                    id = ids.get(i++);
+                    id = mvtFeature.getId();
                 }
 
                 //TODO: also transform properties
@@ -97,19 +96,6 @@ public class MvtUtils {
         return features;
     }
 
-    private static List<Long> getIds(byte[] mvtTile, String layerName) throws IOException {
-        final PrecisionModel precisionModel = new PrecisionModel();
-        final PackedCoordinateSequenceFactory coordinateSequenceFactory =
-                new PackedCoordinateSequenceFactory(PackedCoordinateSequenceFactory.DOUBLE);
-        var geometryFactory = new GeometryFactory(precisionModel, 0, coordinateSequenceFactory);
-        var result = MvtReader.loadMvt(new ByteArrayInputStream(mvtTile), geometryFactory,
-                new TagKeyValueMapConverter(true, ID_KEY));
-
-        var layer = result.getLayers().stream().filter(f -> f.getName().equals(layerName)).findFirst().get();
-        return layer.getGeometries().stream().mapToLong(f -> (long)((LinkedHashMap<String, Object>)f.getUserData()).get(ID_KEY)).
-                boxed().collect(Collectors.toList());
-    }
-
     //TODO: combine decodeMvt and decodeMvt2 to get correct features
     /* Ids are present but geometries of type polygon can have missing vertices and can be wrong */
     private static MapboxVectorTile decodeMvt2(byte[] mvtTile) throws IOException {
```

Or do you think, in your experience, that the `io.github.sebasbaumh.mapbox.vectortile` is more robust than the `no.ecc` one?

**Comment by springmeyer** [comment]
Just ran into what looks like a bug with `getIds`:

Running the CLI against `test/fixtures/bing/mvt/4-12-6.mvt` fails with:

```
java -jar build/libs/mvt2mlt-1.0-SNAPSHOT.jar -mvt ../../test/fixtures/bing/mvt/4-12-6.mvt -output output/
Converting ../../test/fixtures/bing/mvt/4-12-6.mvt to output/4-12-6.mlt
java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.mlt.converter.mvt.MvtUtils.decodeMvt(MvtUtils.java:70)
	at com.mlt.converter.mvt.MvtUtils.decodeMvt(MvtUtils.java:24)
	at com.mlt.converter.MltCliAdapter.main(MltCliAdapter.java:112)
```

the `ids` variable is `[0, 0, 0, 0, 0, 0]`.

@mactrem any reason we can't move away from from using `io.github.sebasbaumh.mapbox.vectortile`?

**Comment by springmeyer** [comment]
Solved by https://github.com/maplibre/maplibre-tile-spec/pull/111
