### ISSUE TITLE
Encoding error: IndexOutOfBoundsException: Index 6 out of bounds for length 6

### ISSUE THREAD

**Issue by springmeyer** [maplibre/maplibre-tile-spec#74]
Running the command locally:

> java -jar ./converter/java/build/libs/mvt2mlt-1.0-SNAPSHOT.jar -mvt test/fixtures/bing/4-12-6.mvt -mlt test/expected/bing/4-12-6.mlt

Hits:

```
java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.mlt.converter.mvt.MvtUtils.decodeMvt(MvtUtils.java:69)
	at com.mlt.converter.mvt.MvtUtils.decodeMvt(MvtUtils.java:24)
	at com.mlt.converter.MltCliAdapter.main(MltCliAdapter.java:189)
```

**Comment by springmeyer** [comment]
This is solved/gone in main. I think the vector tile library upgrade fixed it: #111
